import React from 'react';
import type { ColorValue } from 'react-native';
import {
  Activity,
  ArrowLeft,
  ArrowRight,
  Banknote,
  Bell,
  Bookmark,
  Briefcase,
  Building,
  Calendar,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronRight,
  CircleCheck,
  ClipboardPaste,
  Clock,
  CloudUpload,
  Code,
  Ellipsis,
  ExternalLink,
  FileText,
  Flame,
  GitBranch,
  Globe,
  HardDrive,
  Heart,
  House,
  Info,
  Leaf,
  Link,
  MapPin,
  MessageCircle,
  MessagesSquare,
  Pencil,
  Plus,
  Search,
  Send,
  SlidersHorizontal,
  Sparkles,
  Star,
  TrendingUp,
  User,
  UserSearch,
  X,
  Zap,
  type LucideIcon,
} from 'lucide-react-native';

const MAP: Record<string, LucideIcon> = {
  'arrow-back': ArrowLeft,
  'arrow-forward': ArrowRight,
  'auto-awesome': Sparkles,
  bolt: Zap,
  calendar: Calendar,
  check: Check,
  'check-circle': CircleCheck,
  'content-paste': ClipboardPaste,
  'chevron-right': ChevronRight,
  'chevron-down': ChevronDown,
  description: FileText,
  domain: Building,
  'done-all': CheckCheck,
  'file-upload': CloudUpload,
  info: Info,
  link: Link,
  'person-search': UserSearch,
  public: Globe,
  schedule: Clock,
  send: Send,
  spa: Leaf,
  'task-alt': CircleCheck,
  github: GitBranch,
  'google-drive': HardDrive,
  flame: Flame,
  search: Search,
  bell: Bell,
  bookmark: Bookmark,
  'options-outline': SlidersHorizontal,
  'location-outline': MapPin,
  'briefcase-outline': Briefcase,
  'heart-outline': Heart,
  'chatbubble-outline': MessageCircle,
  'ellipsis-horizontal': Ellipsis,
  pencil: Pencil,
  home: House,
  'home-outline': House,
  discussions: MessagesSquare,
  'discussions-outline': MessagesSquare,
  activity: Activity,
  'activity-outline': Activity,
  person: User,
  'person-outline': User,
  sparkle: Sparkles,
  'cash-outline': Banknote,
  close: X,
  'code-outline': Code,
  'star-outline': Star,
  'open-outline': ExternalLink,
  add: Plus,
  'trending-up': TrendingUp,
};

export type GlyphProps = {
  name: keyof typeof MAP | string;
  size?: number;
  color?: ColorValue;
};

export function Glyph({ name, size = 18, color = '#161616' }: GlyphProps) {
  const Icon = MAP[name] ?? Info;
  return <Icon size={size} color={color} strokeWidth={2} />;
}
